// Thin WC Store API client with Cart-Token + Nonce persistence on disk.
// Docs: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/README.md

import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const BASE = process.env.ITALMARKET_WC_URL || "https://shop.italmarket.com.ar";
const STATE_DIR = path.join(os.homedir(), ".italmarket-mcp");
const STATE_FILE = path.join(STATE_DIR, "state.json");

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
  } catch {
    return { cartToken: null, nonce: null };
  }
}

function saveState(state) {
  fs.mkdirSync(STATE_DIR, { recursive: true });
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

let state = loadState();

const SITE_URL = process.env.ITALMARKET_SITE_URL || "http://localhost:3000";

// Serialize all Store API requests so concurrent tool calls can't interleave
// reads/writes to the shared cart_token / nonce state. Tool calls from a real
// MCP client are usually sequential, but our own self-heal + pairing flows
// compose multiple requests, and we don't want two of those to race.
let chain = Promise.resolve();
function serialized(fn) {
  const next = chain.then(fn, fn);
  chain = next.catch(() => {});
  return next;
}

export function resetCart() {
  state = { cartToken: null, nonce: null };
  saveState(state);
}

export function getState() {
  return { ...state };
}

/**
 * Exchange a 6-digit pairing code (generated by the Next.js site) for the
 * browser's current Cart-Token, then adopt it as our own. After this call,
 * the MCP and the browser share the same WooCommerce cart.
 */
export function pairWithBrowser(code) {
  return serialized(async () => {
    const res = await fetch(`${SITE_URL}/api/cart/pair?code=${encodeURIComponent(code)}`, {
      method: "GET",
      headers: { Accept: "application/json" },
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      throw new Error(
        `Pairing failed (${res.status}): ${data?.error || res.statusText}. ` +
          `¿Está corriendo el sitio en ${SITE_URL}?`,
      );
    }
    if (!data.cart_token) throw new Error("Pairing response missing cart_token");
    state.cartToken = data.cart_token;
    state.nonce = null;
    saveState(state);
    // Prime the nonce: Woo issues one in the headers of every Store API
    // response and requires it on subsequent writes.
    try {
      await rawRequest("GET", "/cart");
    } catch {
      /* non-fatal */
    }
    return { site: SITE_URL, cartToken: data.cart_token };
  });
}

/**
 * Push our current Cart-Token to the browser (reverse pairing). Useful if
 * the MCP already has a cart set up and we want the site to adopt it.
 * Note: this sets the cookie on the Next.js server but the browser must
 * reload (or poll) to pick it up.
 */
export async function pushTokenToBrowser() {
  if (!state.cartToken) throw new Error("No hay cart_token local para enviar.");
  const res = await fetch(`${SITE_URL}/api/cart/pair`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ cart_token: state.cartToken }),
  });
  if (!res.ok) throw new Error(`Push failed: ${res.status}`);
  return { site: SITE_URL };
}

function request(method, pathname, opts = {}) {
  return serialized(async () => {
    try {
      return await rawRequest(method, pathname, opts);
    } catch (e) {
      // Self-heal: if Woo rejects for missing/invalid nonce, refresh it with
      // a GET /cart (which echoes a fresh Nonce header) and retry once.
      const isNonceError =
        e?.status === 401 &&
        (e?.data?.code === "woocommerce_rest_missing_nonce" ||
          e?.data?.code === "woocommerce_rest_invalid_nonce");
      if (!isNonceError || pathname === "/cart") throw e;
      await rawRequest("GET", "/cart");
      return rawRequest(method, pathname, opts);
    }
  });
}

async function rawRequest(method, pathname, { body, query } = {}) {
  const url = new URL(`${BASE}/wp-json/wc/store/v1${pathname}`);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    }
  }
  const headers = { Accept: "application/json" };
  if (body) headers["Content-Type"] = "application/json";
  if (state.cartToken) headers["Cart-Token"] = state.cartToken;
  if (state.nonce) headers["Nonce"] = state.nonce;

  const res = await fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  // Always capture refreshed tokens, even on errors.
  const newCart = res.headers.get("cart-token");
  const newNonce = res.headers.get("nonce");
  let changed = false;
  if (newCart && newCart !== state.cartToken) {
    state.cartToken = newCart;
    changed = true;
  }
  if (newNonce && newNonce !== state.nonce) {
    state.nonce = newNonce;
    changed = true;
  }
  if (changed) saveState(state);

  const text = await res.text();
  const data = text ? JSON.parse(text) : null;

  if (!res.ok) {
    const msg = data?.message || res.statusText;
    const err = new Error(`Store API ${method} ${pathname} → ${res.status}: ${msg}`);
    err.status = res.status;
    err.data = data;
    throw err;
  }
  return data;
}

// ---------- Products ----------

export function searchProducts(query, { per_page = 10, category } = {}) {
  return request("GET", "/products", {
    query: { search: query, per_page, category },
  });
}

export function getProduct(idOrSlug) {
  if (/^\d+$/.test(String(idOrSlug))) {
    return request("GET", `/products/${idOrSlug}`);
  }
  return request("GET", "/products", { query: { slug: idOrSlug } }).then(
    (arr) => (Array.isArray(arr) ? arr[0] ?? null : null),
  );
}

// ---------- Cart ----------

export function getCart() {
  return request("GET", "/cart");
}

export function addCartItem(id, quantity = 1, variation) {
  return request("POST", "/cart/add-item", {
    body: { id, quantity, variation },
  });
}

export function updateCartItem(key, quantity) {
  return request("POST", "/cart/update-item", { body: { key, quantity } });
}

export function removeCartItem(key) {
  return request("POST", "/cart/remove-item", { body: { key } });
}

export async function clearCart() {
  await request("DELETE", "/cart/items");
  return request("GET", "/cart");
}

export function applyCoupon(code) {
  return request("POST", "/cart/apply-coupon", { body: { code } });
}

export function removeCoupon(code) {
  return request("POST", "/cart/remove-coupon", { body: { code } });
}

export function getCheckoutUrl() {
  return `${BASE}/finalizar-compra/`;
}

export function getCartUrl() {
  return `${BASE}/carrito/`;
}
