import type { Recipe } from "@/lib/recipes/types";

export const cacioEPepe: Recipe = {
  slug: "cacio-e-pepe",
  title: "Cacio e pepe",
  italianTitle: "Tonnarelli cacio e pepe",
  summary:
    "Tres ingredientes, dos grados de dificultad técnica: la pasta romana más simple y a la vez más difícil.",
  description:
    "Cacio e pepe auténtica: receta romana tradicional con Pecorino Romano DOP, pimienta negra y pasta. Técnica para lograr la crema perfecta sin grumos, paso a paso.",
  image: "/images/recipes/cacio-e-pepe.jpg",
  imageAlt: "Plato de tonnarelli cacio e pepe con pecorino romano y pimienta negra molida",
  region: "Lazio",
  prepTimeMin: 5,
  cookTimeMin: 12,
  servings: 2,
  difficulty: "media",
  category: "pasta",
  keywords: [
    "cacio e pepe",
    "cacio pepe",
    "pasta cacio e pepe",
    "pasta romana",
    "pecorino y pimienta",
    "receta cacio e pepe",
  ],
  intro: [
    "Cacio e pepe significa literalmente queso y pimienta. Junto con la carbonara y la amatriciana, es uno de los tres clásicos romanos de pasta. Su dificultad no está en la lista de ingredientes — son tres — sino en la técnica: lograr que el pecorino se emulsione con el agua de cocción y no forme una pelota pegajosa.",
    "El truco es controlar la temperatura del agua donde mezclás el queso: demasiado caliente, se corta; demasiado fría, no emulsiona.",
  ],
  ingredients: [
    {
      label: "Tonnarelli o spaghetti",
      quantity: 200,
      unit: "g",
      keywords: [
        "tonnarelli",
        "spaghettoni",
        "bucatini",
        "spaghetti",
        "linguine",
        "gragnano",
      ],
      negativeKeywords: ["sin gluten", "gluten free", "al limone", "al tartufo"],
      note: "Los tonnarelli (espaguetis cuadrados, tipo chitarra) son lo tradicional. Spaghetti di Gragnano funcionan perfecto.",
    },
    {
      label: "Pecorino Romano DOP",
      quantity: 120,
      unit: "g",
      keywords: [
        "pecorino",
        "pecorino romano",
        "parmigiano",
        "parmesano",
        "grana padano",
        "caciocavallo",
      ],
      negativeKeywords: ["mermelada", "granada"],
      note: "Ideal: Pecorino Romano DOP. Si no hay, Parmigiano Reggiano emulsiona distinto pero funciona.",
      hero: true,
    },
    {
      label: "Pimienta negra en grano",
      quantity: 1,
      unit: "cda",
      keywords: ["pimienta negra", "pepe nero"],
      negativeKeywords: ["peperoncino"],
      note: "Recién molida gruesa — idealmente en mortero.",
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "Poné agua a hervir con MENOS sal que de costumbre (5 g por litro). El pecorino ya es muy salado y el agua se usará para la crema.",
    "Rallá el pecorino muy fino con un rallador microplane. Reservá 20 g para terminar el plato.",
    "En un mortero o con un molinillo, machacá granos de pimienta hasta obtener un polvo grueso, con partes enteras. La pimienta pre-molida no sirve: pierde aroma.",
    "Tostá la pimienta molida en una sartén amplia, sin aceite, a fuego medio durante 30 segundos. Vas a sentir el aroma — es la señal.",
    "Agregá a la sartén 2 cucharones de agua de cocción de la pasta (el agua ya debe estar hirviendo, con la pasta adentro). Esto crea una base aromática.",
    "Cociná la pasta al dente (1 minuto menos que la caja). Reservá 1 taza de agua de cocción y colá.",
    "En un bowl separado del fuego, mezclá el pecorino con 4 cucharadas de agua de cocción caliente (NO hirviendo — 80 °C máx.). Revolvé con tenedor hasta lograr una pasta densa y brillante, sin grumos. Si se corta, ya no hay vuelta: empezá de nuevo.",
    "Pasá la pasta a la sartén con la pimienta tostada. Revolvé 30 segundos. Apagá el fuego, esperá 1 minuto, y sumá la crema de pecorino. Revolvé enérgicamente. Si está densa, un chorrito más de agua.",
    "Serví de inmediato con el pecorino reservado y más pimienta molida gruesa arriba.",
  ],
  tips: [
    "La emulsión es todo. El enemigo es el calor directo: el queso se corta a 65–70 °C. Trabajá fuera del fuego.",
    "El agua de cocción con almidón (poco salada) es el ingrediente secreto — funciona como ligante.",
    "Pecorino Romano, no parmigiano. Son quesos muy distintos: el pecorino es de oveja, más graso y salado, y emulsiona mejor.",
    "Si la pasta queda seca después de 1 minuto en el plato, es señal de que la crema estaba demasiado densa. La próxima: más agua, menos queso.",
  ],
  history:
    "La cacio e pepe es una receta pastoreril con siglos de historia. Los pastores romanos que transhumaban entre los Apeninos y la campiña llevaban pasta seca, pecorino y granos de pimienta — alimentos que no se echan a perder y dan muchas calorías. Al llegar a destino, hervían la pasta en el agua disponible y la mezclaban con el queso rallado y pimienta. La pimienta, además de sabor, ayudaba a combatir el frío de las noches de montaña. La receta sobrevivió sin cambios hasta hoy: es probablemente uno de los platos de pasta más antiguos que se siguen cocinando igual en Italia.",
  pairingKeywords: [
    "chianti",
    "barolo",
    "sangiovese",
    "frascati",
    "olio",
    "oliva",
    "taggiasca",
    "tartufo",
    "tarallini",
    "aceto balsamico",
  ],
  publishedAt: "2026-04-13",
};
