import type { Recipe } from "@/lib/recipes/types";

export const carbonara: Recipe = {
  slug: "carbonara",
  title: "Pasta carbonara auténtica",
  italianTitle: "Pasta alla carbonara",
  summary:
    "La verdadera carbonara romana: guanciale, huevo, pecorino y pimienta. Sin crema, sin cebolla, sin excusas.",
  description:
    "Receta auténtica de carbonara romana: aprendé a hacer la pasta carbonara original con guanciale, yemas de huevo, Pecorino Romano DOP y pimienta negra recién molida. Técnica paso a paso y consejos para que no se corte.",
  image: "/images/recipes/carbonara.jpg",
  imageAlt: "Plato de pasta carbonara romana con guanciale, yema y pecorino",
  region: "Lazio",
  prepTimeMin: 10,
  cookTimeMin: 15,
  servings: 4,
  difficulty: "media",
  category: "pasta",
  keywords: [
    "carbonara",
    "pasta carbonara",
    "carbonara auténtica",
    "carbonara romana",
    "carbonara sin crema",
    "pasta alla carbonara",
    "receta carbonara original",
  ],
  intro: [
    "La carbonara auténtica tiene cuatro ingredientes — cinco si contás la sal del agua. No lleva crema. No lleva cebolla. No lleva ajo. No lleva panceta ahumada. Y no, tampoco se le suma perejil.",
    "El cremoso característico sale del huevo batido con el queso y el calor residual de la pasta; cualquier desvío convierte el plato en algo delicioso pero distinto. Este es el método original del Lazio.",
  ],
  ingredients: [
    {
      label: "Spaghetti o rigatoni",
      quantity: 400,
      unit: "g",
      keywords: [
        "rigatoni",
        "spaghettoni",
        "bucatini",
        "spaghetti",
        "vermicelli",
        "linguine",
        "gragnano",
      ],
      negativeKeywords: ["sin gluten", "gluten free", "al limone", "al tartufo"],
    },
    {
      label: "Guanciale",
      quantity: 200,
      unit: "g",
      keywords: [
        "guanciale",
        "pancetta",
        "panceta",
        "salumi",
      ],
      negativeKeywords: ["pizza", "daleo", "congelada"],
      note: "Idealmente guanciale; si no conseguís, pancetta tesa no ahumada. El prosciutto cocido argentino NO es sustituto — cambia completamente el plato.",
      hero: true,
    },
    {
      label: "Yemas de huevo",
      quantity: 4,
      unit: "unidades",
      note: "Reservá 1 huevo entero adicional para sumarlo a las yemas.",
    },
    {
      label: "Pecorino Romano DOP",
      quantity: 100,
      unit: "g",
      keywords: [
        "pecorino",
        "pecorino romano",
        "parmigiano",
        "parmesano",
        "grana padano",
        "caciocavallo",
      ],
      negativeKeywords: ["mermelada", "granada"],
      note: "El ideal es Pecorino Romano. Si no hay, Parmigiano Reggiano o un caciocavallo añejo son sustitutos aceptables.",
    },
    {
      label: "Pimienta negra en grano",
      quantity: "a gusto",
      keywords: ["pimienta negra", "pepe nero"],
      negativeKeywords: ["peperoncino"],
      note: "Recién molida, gruesa. Es un ingrediente, no un condimento.",
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "Poné a hervir abundante agua con sal gruesa (10 g por litro). Cocinar la pasta al dente, respetando 1 minuto menos del tiempo de la caja.",
    "Mientras tanto, cortá el guanciale en bastones de 1 cm de ancho, descartando la corteza. En una sartén grande sin aceite, a fuego medio, cociná el guanciale hasta que la grasa se derrita y los trozos queden dorados pero no crocantes (8–10 minutos). Apagá el fuego y dejá la sartén con toda la grasa.",
    "En un bowl, batí las 4 yemas + 1 huevo entero con el Pecorino rallado fino y abundante pimienta negra recién molida. La mezcla debe quedar como una crema espesa, color amarillo intenso. Si queda muy dura, sumá 1 cucharada de agua de cocción.",
    "Cuando la pasta esté al dente, reservá 1 taza de agua de cocción y colá la pasta — pero sin secarla del todo.",
    "Pasá la pasta a la sartén con el guanciale (fuera del fuego). Revolvé 30 segundos para que se impregne. Si la sartén está muy caliente, esperá otro minuto: si el huevo toca temperatura mayor a 65 °C, cuaja y arruinás el plato.",
    "Agregá la mezcla de huevo y queso sobre la pasta. Revolvé enérgicamente. Si está muy densa, sumá agua de cocción de a cucharadas hasta lograr una salsa brillante que nape la pasta.",
    "Serví de inmediato, con más Pecorino y pimienta negra por encima.",
  ],
  tips: [
    "El mayor error es calentar demasiado: el huevo no se cocina, se temperá. Si ves grumos amarillos, bajaste la guardia.",
    "El guanciale no es pancetta ahumada: es carrillada de cerdo curada con pimienta. Si no conseguís guanciale, pancetta tesa (no ahumada) es el sustituto aceptable.",
    "Nunca tires la grasa del guanciale: es parte de la salsa.",
    "Si querés una versión más rica, sumá una yema extra por comensal.",
  ],
  history:
    "El origen de la carbonara está en disputa. La teoría más aceptada la sitúa en Roma, en la posguerra (1944–1945), cuando los soldados estadounidenses llevaban raciones de huevo en polvo y panceta que los cocineros romanos combinaban con spaghetti. Otra versión, más romántica, dice que era el plato de los carbonai, los leñadores que hacían carbón en los Apeninos y lo cocinaban con los ingredientes que tenían: huevos, queso y guanciale. La primera receta escrita aparece recién en 1954, en la revista La Cucina Italiana. Hoy está protegida culturalmente — aunque no legalmente — por la Accademia Italiana della Cucina.",
  pairingKeywords: [
    "chianti",
    "barolo",
    "sangiovese",
    "tarallini",
    "grissini",
    "aceto balsamico",
    "tartufo",
    "olio",
    "oliva",
    "taggiasca",
  ],
  publishedAt: "2026-04-13",
};
