import type { Recipe } from "@/lib/recipes/types";

export const pappardelleAlRagu: Recipe = {
  slug: "pappardelle-al-ragu",
  title: "Pappardelle al ragù alla bolognese",
  italianTitle: "Pappardelle al ragù",
  summary:
    "El ragù de Bolonia auténtico: carne, tomate y vino cocinados 3 horas. Con pappardelle anchas que atrapan la salsa.",
  description:
    "Receta tradicional de pappardelle al ragù alla bolognese: aprendé a hacer el ragù original italiano con carne picada, soffritto, tomate pelado, vino y leche, cocinado a fuego lento 3 horas. Servido con pappardelle al huevo Divella.",
  image: "/images/recipes/pappardelle-al-ragu.jpg",
  imageAlt: "Plato de pappardelle con ragù bolognese y parmigiano rallado",
  region: "Emilia-Romagna",
  prepTimeMin: 20,
  cookTimeMin: 180,
  servings: 6,
  difficulty: "media",
  category: "pasta",
  keywords: [
    "pappardelle al ragu",
    "ragu bolognese",
    "pasta al ragu",
    "ragu alla bolognese",
    "bolognese auténtica",
    "pappardelle bolognese",
  ],
  intro: [
    "El ragù alla bolognese NO es lo mismo que la salsa bolognesa argentina. Lleva dos carnes, poco tomate, una taza de leche y tres horas a fuego bajo. La receta oficial está registrada desde 1982 en la Accademia Italiana della Cucina — y sí, es larga.",
    "En Bolonia nunca se sirve con spaghetti — es un sacrilegio. Va con pappardelle, tagliatelle al huevo o lasagna, porque la salsa es espesa y necesita superficie de pasta ancha para adherir.",
  ],
  ingredients: [
    {
      label: "Pappardelle al uovo",
      quantity: 500,
      unit: "g",
      keywords: ["pappardelle", "tagliatelle", "fettuccine al uovo", "fettuccine"],
      negativeKeywords: ["sin gluten", "gluten free", "al tartufo", "al limone"],
      hero: true,
    },
    {
      label: "Carne picada de ternera",
      quantity: 300,
      unit: "g",
      note: "Molida gruesa, no fina. Preferiblemente de bife angosto o cuadril.",
    },
    {
      label: "Carne picada de cerdo (o panceta picada)",
      quantity: 150,
      unit: "g",
      note: "Sin la panceta fresca el ragù pierde complejidad. Si no conseguís, sumá más ternera y un chorro de olio extra.",
    },
    {
      label: "Cebolla",
      quantity: 1,
      unit: "mediana",
      note: "Picada muy fina.",
    },
    {
      label: "Zanahoria",
      quantity: 1,
      unit: "mediana",
      note: "Picada muy fina.",
    },
    {
      label: "Apio",
      quantity: 1,
      unit: "rama",
      note: "Picada muy fina.",
    },
    {
      label: "Pomodoro pelato San Marzano",
      quantity: 400,
      unit: "g",
      keywords: ["san marzano", "pomodori pelati", "pomodoro pelati", "pelati", "passata"],
      negativeKeywords: ["doppio concentrato", "arrabbiata", "tartufo"],
    },
    {
      label: "Doppio concentrato di pomodoro",
      quantity: 2,
      unit: "cdas",
      keywords: ["doppio concentrato", "concentrato pomodoro", "concentrato"],
    },
    {
      label: "Vino blanco seco",
      quantity: 200,
      unit: "ml",
      note: "Idealmente un Prosecco seco. No uses vino tinto — en Bolonia va blanco.",
    },
    {
      label: "Leche entera",
      quantity: 200,
      unit: "ml",
      note: "Ablanda la acidez del tomate y redondea las carnes. No se omite.",
    },
    {
      label: "Aceite de oliva extra virgen",
      quantity: 3,
      unit: "cdas",
      keywords: ["olio extra virgen", "olio extravergine", "olio evo", "aceite de oliva", "dante"],
      negativeKeywords: ["tarallini", "tartufo", "al limone"],
    },
    {
      label: "Parmigiano Reggiano para servir",
      quantity: 80,
      unit: "g",
      keywords: ["parmigiano reggiano", "parmigiano", "parmesano", "grana padano", "caciocavallo"],
      negativeKeywords: ["mermelada", "granada"],
    },
    {
      label: "Sal y pimienta negra",
      quantity: "a gusto",
      keywords: ["pimienta negra", "pepe nero"],
      negativeKeywords: ["peperoncino"],
    },
  ],
  steps: [
    "Picá cebolla, zanahoria y apio muy finos — el soffritto debe ser casi invisible en la salsa final.",
    "En una olla de fondo pesado, calentá el aceite de oliva a fuego medio. Sumá el soffritto y cociná 10 minutos hasta que se ablande, sin dorar.",
    "Agregá la carne de ternera y cerdo. Rompela con cuchara de madera y cociná hasta que pierda el color rosado. Salá ligero.",
    "Subí el fuego. Sumá el vino blanco y dejá evaporar completamente — 5 minutos revolviendo.",
    "Agregá el doppio concentrato y revolvé 2 minutos para que se tueste y concentre.",
    "Sumá los pelati rotos con la mano, 1 taza de agua y una pizca de sal. Llevá a hervor, bajá al mínimo.",
    "Cociná a fuego muy bajo, semi-tapado, al menos 2 horas. Revolvé cada 20 minutos. Si se seca, sumá agua caliente de a poco.",
    "En la última hora, agregá la leche en tandas. Dejá integrar lentamente — va a parecer cortada pero se estabiliza.",
    "Rectificá sal y pimienta al final. La salsa debe estar densa, aceitosa en la superficie, carnosa.",
    "Herví las pappardelle al dente en abundante agua con sal. Colá reservando agua de cocción.",
    "Pasá la pasta a la olla del ragù (fuera del fuego). Mezclá 30 segundos, sumando agua de cocción si hace falta.",
    "Serví con abundante Parmigiano rallado encima.",
  ],
  tips: [
    "Tres horas mínimo. Si cortás antes, no es ragù bolognese: es salsa boloñesa.",
    "La leche es opcional para puristas pero la receta oficial del 1982 la lleva.",
    "Mejor al día siguiente: dejalo reposar 12 h en heladera. El sabor se asienta.",
    "Se congela perfecto en frascos individuales por 3 meses.",
  ],
  history:
    "El ragù alla bolognese tiene su primera receta escrita en 1891, en La scienza in cucina e l'arte di mangiar bene de Pellegrino Artusi, con el nombre de maccheroni alla bolognese. Pero es en 1982 cuando la Accademia Italiana della Cucina deposita la receta oficial ante la Cámara de Comercio de Bolonia, especificando proporciones, cortes de carne, y la prohibición explícita de servirlo con spaghetti. Bolonia es también la capital europea del tortellino y de la mortadela — su cocina se define por la riqueza de las carnes y la pasta al huevo. El ragù napolitano, en cambio, lleva trozos de carne enteros y tomate fresco, es otro plato completamente distinto.",
  pairingKeywords: [
    "chianti",
    "sangiovese",
    "barolo",
    "parmigiano",
    "aceto balsamico",
    "olio extra virgen",
    "prosecco",
    "tarallini",
  ],
  publishedAt: "2026-04-13",
};
