import type { Recipe } from "@/lib/recipes/types";

export const pestoGenovese: Recipe = {
  slug: "pesto-genovese",
  title: "Pesto alla genovese auténtico",
  italianTitle: "Pesto alla genovese",
  summary:
    "El pesto original de Liguria: albahaca genovese, piñones, ajo, Parmigiano Reggiano, Pecorino y aceite de oliva — sin procesadora.",
  description:
    "Receta tradicional de pesto alla genovese: aprendé a hacer el pesto italiano auténtico con albahaca, piñones, ajo, Parmigiano Reggiano DOP, Pecorino y aceite de oliva extra virgen. Técnica de mortero y consejos para el verde perfecto.",
  image: "/images/recipes/pesto-genovese.jpg",
  imageAlt: "Pesto alla genovese en mortero con albahaca, piñones y Parmigiano",
  region: "Liguria",
  prepTimeMin: 15,
  cookTimeMin: 0,
  servings: 4,
  difficulty: "fácil",
  category: "salsa",
  keywords: [
    "pesto genovese",
    "pesto alla genovese",
    "pesto auténtico",
    "pesto casero",
    "pesto con albahaca",
    "salsa pesto italiana",
  ],
  intro: [
    "El pesto no se cocina: se machaca. La palabra viene de pestare, golpear con el mortero. La receta oficial tiene siete ingredientes, siete pasos y ninguna licuadora — el calor del motor quema la albahaca y el verde se vuelve marrón.",
    "Esta versión sigue el protocolo del Consorzio del Pesto Genovese: albahaca de Pra', piñones, ajo de Vessalico, Parmigiano Reggiano DOP añejado al menos 30 meses, Pecorino Sardo, sal gruesa y aceite de oliva de la Riviera Ligure.",
  ],
  ingredients: [
    {
      label: "Albahaca fresca",
      quantity: 50,
      unit: "g",
      note: "Hojas jóvenes y pequeñas, sin lavar (o lavadas y bien secas). No la vendemos en tienda — buscala en tu verdulería.",
    },
    {
      label: "Piñones",
      quantity: 30,
      unit: "g",
      keywords: ["piñones", "pinoli", "pine nuts"],
      note: "Si no conseguís piñones, alternativamente podés usar un frasco de pesto alla genovese hecho como atajo.",
    },
    {
      label: "Ajo",
      quantity: 1,
      unit: "diente",
    },
    {
      label: "Parmigiano Reggiano DOP",
      quantity: 40,
      unit: "g",
      keywords: [
        "parmigiano reggiano",
        "parmigiano",
        "parmesano reggiano",
        "parmesano",
        "grana padano",
        "caciocavallo",
      ],
      negativeKeywords: ["mermelada", "granada"],
      hero: true,
    },
    {
      label: "Pecorino Sardo DOP",
      quantity: 20,
      unit: "g",
      keywords: ["pecorino sardo", "pecorino romano", "pecorino"],
      negativeKeywords: ["mermelada", "granada"],
      note: "Si no conseguís Sardo, Pecorino Romano funciona. En su defecto, más Parmigiano.",
    },
    {
      label: "Aceite de oliva extra virgen",
      quantity: 100,
      unit: "ml",
      keywords: [
        "olio extra virgen",
        "olio extravergine",
        "olio evo",
        "olio di oliva",
        "aceite de oliva",
        "extra virgen",
        "taggiasca",
        "toscano",
        "dante",
      ],
      negativeKeywords: ["tarallini", "tartufo", "al limone"],
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "Machacá el diente de ajo con unos granos de sal gruesa en el mortero, hasta que se haga una pasta.",
    "Agregá los piñones y seguí machacando hasta que se integren con el ajo.",
    "Sumá las hojas de albahaca de a puñados. El movimiento correcto es circular, aplastando las hojas contra las paredes del mortero — no golpeando. Vas a ver que la albahaca suelta un jugo verde intenso: esa es la señal de que vas bien.",
    "Cuando tengas una pasta verde homogénea, agregá los dos quesos rallados finos y mezclá con la mano del mortero.",
    "Finalmente, incorporá el aceite de oliva en hilo, revolviendo con una cuchara (no con el mortero) hasta obtener una salsa cremosa pero que no llegue a estar emulsionada como una mayonesa.",
    "Probá y ajustá sal. El pesto debe usarse crudo, sin calentar. Condimentá la pasta con un par de cucharadas del agua de cocción caliente para aflojarlo y servir.",
  ],
  tips: [
    "Si no tenés mortero, usá una procesadora con cuchillas de plástico y pulsá en tandas cortas para no calentar. Resultado: 8 de 10 vs. el original.",
    "La pasta que mejor va con pesto no son los spaghetti, son los trofie o trenette. Se agrega también papa hervida cortada en dados y chauchas a la cocción.",
    "Guardá el pesto cubierto con una capa de aceite de oliva; dura 5 días en heladera. O congelalo en cubitera.",
    "Si querés que mantenga el verde intenso, blanqueá las hojas 5 segundos en agua hirviendo antes de machacar (es herejía en Génova, pero funciona).",
  ],
  history:
    "La receta moderna de pesto se codificó a mediados del siglo XIX en Liguria, pero sus raíces son más antiguas: en Roma antigua ya existía el moretum, una pasta de hierbas, ajo y queso que describe Virgilio en sus Geórgicas. El pesto genovés tal como lo conocemos requiere la albahaca de Pra', un barrio al oeste de Génova donde el microclima produce hojas pequeñas, dulces y sin notas mentoladas. En 2005 se creó el Consorzio del Pesto Genovese que estandariza ingredientes, proporciones y técnica; desde 2008 existe un campeonato mundial del pesto al mortero.",
  pairingKeywords: [
    "trofie",
    "trenette",
    "linguine",
    "spaghetti",
    "gragnano",
    "pesto",
    "vermentino",
    "prosecco",
    "valdobbiadene",
    "taggiasca",
    "tarallini",
    "olio",
  ],
  publishedAt: "2026-04-13",
};
