import type { Recipe } from "@/lib/recipes/types";

export const pizzaMargherita: Recipe = {
  slug: "pizza-margherita",
  title: "Pizza margherita napoletana",
  italianTitle: "Pizza margherita",
  summary:
    "La pizza más famosa del mundo en tres colores: pomodoro, mozzarella y albahaca. Masa napoletana con harina italiana.",
  description:
    "Receta auténtica de pizza margherita napoletana: aprendé a hacer la masa italiana tradicional con harina pizza napoletana, pomodoro San Marzano, mozzarella fior di latte o burrata, albahaca fresca y aceite de oliva extra virgen. Técnica paso a paso y horno casero.",
  image: "/images/recipes/pizza-margherita.jpg",
  imageAlt: "Pizza margherita napoletana con pomodoro, mozzarella y albahaca",
  region: "Campania",
  prepTimeMin: 30,
  cookTimeMin: 8,
  servings: 4,
  difficulty: "media",
  category: "pizza",
  keywords: [
    "pizza margherita",
    "pizza napoletana",
    "pizza margherita casera",
    "pizza italiana auténtica",
    "masa pizza napoletana",
    "margherita receta",
  ],
  intro: [
    "La margherita es la pizza de los tres colores de la bandera italiana: rojo del pomodoro, blanco de la mozzarella, verde de la albahaca. Fue creada en 1889 en Nápoles por el pizzaiolo Raffaele Esposito para la reina Margherita de Saboya.",
    "La clave está en la masa: harina fuerte tipo 00, hidratación alta (65%), levado largo a baja temperatura. El resto son cuatro ingredientes italianos de calidad y un horno bien caliente.",
  ],
  ingredients: [
    {
      label: "Harina tipo 00 para pizza napoletana",
      quantity: 500,
      unit: "g",
      keywords: ["harina pizza napoletana", "harina pizza", "farina 00", "caputo", "harina oro"],
      negativeKeywords: ["libre de gluten", "sin gluten"],
      hero: true,
    },
    {
      label: "Agua fría",
      quantity: 325,
      unit: "ml",
    },
    {
      label: "Sal fina",
      quantity: 10,
      unit: "g",
    },
    {
      label: "Levadura fresca",
      quantity: 2,
      unit: "g",
      note: "O 0,7 g de levadura seca instantánea. Poca — el secreto es el tiempo, no la levadura.",
    },
    {
      label: "Pomodoro pelato San Marzano",
      quantity: 300,
      unit: "g",
      keywords: ["san marzano", "pomodori pelati", "pomodoro pelati", "pelati", "passata"],
      negativeKeywords: ["doppio concentrato", "arrabbiata", "tartufo"],
    },
    {
      label: "Mozzarella fior di latte o burrata",
      quantity: 250,
      unit: "g",
      keywords: ["burrata", "bocconcino", "mozzarella", "fior di latte"],
      negativeKeywords: ["pizza", "daleo", "congelada"],
      note: "La mozzarella de búfala es la tradicional; si no conseguís, burrata o bocconcino escurridos funcionan perfecto.",
    },
    {
      label: "Aceite de oliva extra virgen",
      quantity: 30,
      unit: "ml",
      keywords: ["olio extra virgen", "olio extravergine", "olio evo", "aceite de oliva", "dante"],
      negativeKeywords: ["tarallini", "tartufo", "al limone"],
    },
    {
      label: "Albahaca fresca",
      quantity: 10,
      unit: "hojas",
      note: "Hojas enteras, agregadas después de hornear.",
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "Mezclá la harina con el agua fría y dejá reposar 20 minutos (autolisis). Esto hidrata el gluten antes de trabajar la masa.",
    "Agregá la levadura y la sal. Amasá 10 minutos hasta que la masa esté lisa y elástica. Se despega de las manos cuando está lista.",
    "Formá una bola, cubrí con film y dejá levar a temperatura ambiente 2 horas.",
    "Dividí la masa en 4 bollos de ~210 g. Formá bolas apretadas con tensión superficial. Dejá levar 6–8 horas más a temperatura ambiente, o 24 horas en heladera (mejor sabor).",
    "Precalentá el horno a máxima potencia (250–280 °C) con piedra para pizza o placa invertida adentro — al menos 45 minutos.",
    "Estirá cada bollo con las manos, nunca con palo: empujá desde el centro hacia afuera, dejando el borde (cornicione) sin tocar. Diámetro final: 28–30 cm.",
    "Rompé los pomodori pelati con la mano, mezclá con sal y una cucharada de olio. Distribuí una capa fina sobre la masa, dejando 2 cm de borde libre.",
    "Horneá 5 minutos sobre la piedra. Sacá, agregá la mozzarella cortada en trozos, las hojas de albahaca y un hilo de olio. Volvé al horno 2–3 minutos más hasta que la mozzarella se funda.",
    "Serví inmediatamente — la pizza napoletana se come caliente y blanda en el centro (no crocante).",
  ],
  tips: [
    "La harina tipo 00 es imprescindible: tiene el gluten perfecto para leudado largo. Harina común hace pizza tipo argentina.",
    "Si tu horno no llega a 280 °C, usá piedra refractaria — le da el calor residual que simula el horno a leña.",
    "No sobrecargar con ingredientes: la margherita napoletana es frugal por diseño.",
    "El levado en frío 24 h hace una masa más digerible y con más sabor por fermentación lenta.",
  ],
  history:
    "La pizza margherita fue inventada el 11 de junio de 1889 en Nápoles por Raffaele Esposito, propietario de la pizzería Pietro il Pizzaiolo, en honor a la reina Margherita de Saboya durante una visita real. Esposito creó tres pizzas y la que llevaba los colores de la bandera italiana unificada — pomodoro, mozzarella y basilico — quedó con el nombre de la reina. En 2004 la pizza napoletana recibió la denominación STG (Specialità Tradizionale Garantita) de la Unión Europea, que especifica harina tipo 00, tiempo de leudado mínimo de 8 horas, horno a leña a 485 °C y diámetro máximo de 35 cm. La Associazione Verace Pizza Napoletana certifica pizzerías en todo el mundo que respetan el protocolo.",
  pairingKeywords: [
    "olio extra virgen",
    "aceto balsamico",
    "prosecco",
    "chianti",
    "tarallini",
    "burrata",
    "olive",
    "taggiasca",
  ],
  publishedAt: "2026-04-13",
};
