import type { Recipe } from "@/lib/recipes/types";

export const risottoAllaMilanese: Recipe = {
  slug: "risotto-alla-milanese",
  title: "Risotto alla milanese",
  italianTitle: "Risotto alla milanese",
  summary:
    "El risotto más famoso de Italia: arroz carnaroli, azafrán, mantequilla, parmigiano y caldo. Un plato amarillo, cremoso y elegante.",
  description:
    "Receta original del risotto alla milanese: aprendé la técnica tradicional con arroz carnaroli, azafrán, cebolla, vino blanco, caldo de carne y parmigiano reggiano. Plato emblema de Lombardía, paso a paso.",
  image: "/images/recipes/risotto-alla-milanese.jpg",
  imageAlt: "Plato de risotto alla milanese dorado con hebras de azafrán y parmigiano",
  region: "Lombardia",
  prepTimeMin: 10,
  cookTimeMin: 25,
  servings: 4,
  difficulty: "media",
  category: "risotto",
  keywords: [
    "risotto alla milanese",
    "risotto milanes",
    "receta risotto",
    "risotto con azafran",
    "riso carnaroli receta",
    "risotto italiano",
  ],
  intro: [
    "El risotto alla milanese es el plato más famoso de Lombardía. Su color amarillo intenso viene del azafrán — especia valiosa que en Milán se usa desde el 1500, cuando un vidriero español la agregó por broma a un risotto en una boda.",
    "La técnica del risotto se basa en tres pasos: tostar el arroz, agregar líquido caliente de a poco, y mantecare (montar con manteca y queso fuera del fuego). El arroz adecuado es el carnaroli, con más almidón que el arborio.",
  ],
  ingredients: [
    {
      label: "Riso carnaroli",
      quantity: 320,
      unit: "g",
      keywords: ["riso carnaroli", "carnaroli", "riso arborio", "arborio", "riso"],
      hero: true,
    },
    {
      label: "Caldo de carne",
      quantity: 1.2,
      unit: "L",
      note: "Casero idealmente. Debe estar caliente a lo largo de toda la cocción.",
    },
    {
      label: "Cebolla blanca",
      quantity: 1,
      unit: "pequeña",
      note: "Picada muy fina.",
    },
    {
      label: "Azafrán en hebras",
      quantity: 1,
      unit: "g",
      note: "Hebras, NO polvo. Tostá ligero y dejá infusionar 10 minutos en 50 ml de caldo caliente.",
    },
    {
      label: "Vino blanco seco",
      quantity: 100,
      unit: "ml",
      note: "Un Prosecco brut o un blanco seco sin barrica.",
    },
    {
      label: "Manteca",
      quantity: 60,
      unit: "g",
      note: "30 g para el soffritto, 30 g fríos para la mantecatura final.",
    },
    {
      label: "Parmigiano Reggiano",
      quantity: 80,
      unit: "g",
      keywords: ["parmigiano reggiano", "parmigiano", "parmesano", "grana padano", "caciocavallo"],
      negativeKeywords: ["mermelada", "granada"],
    },
    {
      label: "Médula de res (opcional, tradicional)",
      quantity: 30,
      unit: "g",
      note: "La receta original milanesa la lleva — agrega profundidad. Pedila en la carnicería.",
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "Tostá las hebras de azafrán 30 segundos en una sartén sin aceite. Dejá infusionar en 50 ml de caldo caliente 10 minutos.",
    "En una cacerola ancha y pesada, derretí 30 g de manteca a fuego medio. Sumá la cebolla picada y cociná 5 minutos sin dorar. Si usás médula, agregala acá.",
    "Subí el fuego. Tirá el arroz seco a la cacerola y tostá 2–3 minutos revolviendo constantemente, hasta que los granos queden translúcidos con un punto blanco al centro.",
    "Deglacá con el vino blanco. Revolvé hasta que se evapore completamente — el alcohol debe irse.",
    "Empezá a agregar el caldo caliente de a un cucharón. Revolvé con frecuencia, sin parar pero sin apurar. Cuando el arroz absorbió el caldo, agregá el siguiente cucharón.",
    "A la mitad de la cocción (8 minutos), sumá la infusión de azafrán. El color se vuelve amarillo intenso.",
    "Seguí agregando caldo hasta que el arroz esté al dente — 16 a 18 minutos total desde que tostaste. El grano debe ceder pero no deshacerse.",
    "Apagá el fuego. La consistencia debe ser all'onda: si inclinás la cacerola, el risotto fluye formando ondas. Si está seco, sumá medio cucharón más.",
    "Ahora la mantecatura: agregá los 30 g de manteca fría en cubos y el Parmigiano rallado fino. Revolvé enérgicamente 30 segundos con movimiento de muñeca. El risotto se vuelve brillante y cremoso.",
    "Tapá y dejá reposar 2 minutos. Serví inmediatamente, sin queso adicional ni adornos — el risotto alla milanese se come solo, en plato plano extendido.",
  ],
  tips: [
    "Revolver demasiado rompe el almidón externo y queda pegajoso. Revolvé suavemente, con pocas vueltas.",
    "El caldo siempre caliente — si agregás frío, bajás la temperatura del arroz y la cocción se arruina.",
    "La mantecatura es sagrada: fuera del fuego, con manteca fría, 30 segundos intensos. Acá nace la cremosidad.",
    "Si querés una versión vegetariana, usá caldo de verduras y omití la médula.",
    "Se come al momento. Recalentado pierde textura — convertilo en supplì fritos.",
  ],
  history:
    "El risotto alla milanese tiene un origen legendario: en 1574, durante los frescos del Duomo de Milán, un vidriero español apodado Zafferano se ganaba la vida agregando azafrán a los vidrios de los vitrales. Un compañero lo desafió diciendo que hasta al arroz le agregaría azafrán — y Zafferano lo hizo en la boda de la hija de su maestro. El plato gustó y quedó. La primera receta escrita aparece en 1829 en el Nuovo cuoco milanese economico de Felice Luraschi, con médula de ternera y azafrán. Hoy es el acompañamiento tradicional del ossobuco alla milanese, pero también se sirve solo como plato principal. En 2007 la Provincia de Milán registró la receta como PAT (Prodotto Agroalimentare Tradizionale).",
  pairingKeywords: [
    "prosecco",
    "barolo",
    "chianti",
    "sangiovese",
    "aceto balsamico",
    "olio extra virgen",
    "parmigiano",
    "tarallini",
  ],
  publishedAt: "2026-04-13",
};
