import type { Recipe } from "@/lib/recipes/types";

export const salsaPomodoro: Recipe = {
  slug: "salsa-pomodoro",
  title: "Salsa pomodoro casera",
  italianTitle: "Salsa al pomodoro",
  summary:
    "La salsa de tomate italiana auténtica: tres ingredientes, veinte minutos y el secreto del San Marzano.",
  description:
    "Aprendé a hacer salsa pomodoro italiana auténtica en casa: receta tradicional con tomate San Marzano, aceite de oliva extra virgen, albahaca fresca y un diente de ajo. Lista en 20 minutos, ideal para cualquier pasta.",
  image: "/images/recipes/salsa-pomodoro.jpg",
  imageAlt: "Salsa pomodoro italiana casera en una cacerola con albahaca fresca",
  region: "Campania",
  prepTimeMin: 5,
  cookTimeMin: 20,
  servings: 4,
  difficulty: "fácil",
  category: "salsa",
  keywords: [
    "salsa pomodoro",
    "salsa de tomate italiana",
    "salsa pomodoro casera",
    "pomodoro San Marzano",
    "salsa italiana auténtica",
    "cómo hacer salsa pomodoro",
  ],
  intro: [
    "La salsa pomodoro es el alma de la cocina italiana. No lleva cebolla, ni azúcar, ni una lista interminable de condimentos: solo buen tomate, aceite de oliva extra virgen, albahaca fresca y un diente de ajo. Todo el sabor depende de la calidad del tomate — por eso los italianos son fanáticos del San Marzano DOP, cultivado en la llanura volcánica del Vesubio.",
    "Es la salsa base sobre la que se construyen cientos de platos: desde un spaghetti al pomodoro con una hoja de albahaca, hasta la pizza napoletana o una parmigiana di melanzane.",
  ],
  ingredients: [
    {
      label: "Tomate pelado San Marzano",
      quantity: 800,
      unit: "g",
      keywords: [
        "san marzano",
        "pomodori pelati",
        "pomodoro pelati",
        "pelati",
        "passata",
        "pomodorini",
        "datterini",
        "tomate pelado",
        "pomodoro",
      ],
      negativeKeywords: ["doppio concentrato", "arrabbiata", "tartufo"],
      note: "Idealmente San Marzano DOP. Otros pelati italianos o una passata funcionan bien.",
      hero: true,
      suggestedUnits: 2,
    },
    {
      label: "Aceite de oliva extra virgen",
      quantity: 4,
      unit: "cdas",
      keywords: [
        "olio extra virgen",
        "olio extravergine",
        "olio evo",
        "olio di oliva",
        "aceite de oliva",
        "extra virgen",
        "taggiasca",
        "toscano",
        "dante",
      ],
      negativeKeywords: ["tarallini", "tartufo", "al limone"],
    },
    {
      label: "Ajo",
      quantity: 1,
      unit: "diente",
    },
    {
      label: "Albahaca fresca",
      quantity: 8,
      unit: "hojas",
      note: "Idealmente del jardín o del mercado el mismo día.",
    },
    {
      label: "Sal gruesa",
      quantity: "a gusto",
    },
  ],
  steps: [
    "En una olla ancha y de fondo pesado, calentá el aceite de oliva a fuego medio-bajo. Agregá el diente de ajo aplastado (no cortado) y dejá que perfume el aceite durante 1 a 2 minutos, sin que tome color. Si se dora, el sabor se vuelve amargo.",
    "Retirá el ajo y descartalo. Agregá los tomates pelados con todo su jugo. Rompé los tomates con una cuchara de madera — deben quedar trozos, no puré.",
    "Sumá una pizca de sal gruesa y 4 hojas de albahaca. Cociná a fuego bajo, sin tapa, durante 15 a 20 minutos. La salsa está lista cuando el aceite sube a la superficie y forma ojos rojos.",
    "Apagá el fuego, rectificá la sal y agregá las hojas de albahaca restantes recién partidas con las manos (no cortadas con cuchillo, que oxida el verde).",
    "Serví inmediatamente sobre pasta al dente, o guardá en frasco esterilizado hasta 4 días en heladera.",
  ],
  tips: [
    "Nunca agregues azúcar. Si la salsa queda ácida, el problema es el tomate — cambiá de marca.",
    "La proporción ideal es 1 lata de pelati por persona. Mejor que sobre.",
    "Un toque final de aceite de oliva crudo justo antes de servir cambia la textura y el aroma.",
    "Si la vas a usar para pizza, cociná 5 minutos menos: el horno termina de hacer el trabajo.",
  ],
  history:
    "Aunque el tomate llegó a Europa desde América a mediados del siglo XVI, los italianos tardaron casi 200 años en confiar en él — lo consideraban venenoso. Recién a fines del siglo XVIII aparece en recetarios napolitanos como acompañamiento de pasta. Hoy el tomate San Marzano, cultivado en los suelos volcánicos al sur del Vesubio, tiene denominación de origen protegida (DOP) desde 1996: solo puede llamarse así el producido en 41 comunas específicas de Campania, cosechado a mano y conservado entero o en mitades.",
  pairingKeywords: [
    "spaghetti",
    "spaghettoni",
    "rigatoni",
    "linguine",
    "bucatini",
    "penne",
    "gragnano",
    "parmigiano",
    "parmesano",
    "pecorino",
    "grana",
    "caciocavallo",
    "mozzarella",
    "burrata",
    "chianti",
    "barolo",
    "sangiovese",
    "olio",
    "taggiasca",
  ],
  publishedAt: "2026-04-13",
};
