import type { Recipe } from "@/lib/recipes/types";

export const tiramisu: Recipe = {
  slug: "tiramisu",
  title: "Tiramisú clásico",
  italianTitle: "Tiramisù",
  summary:
    "El tiramisú original del Véneto: mascarpone, café espresso, huevo, cacao y savoiardi. Sin crema de leche, sin gelatina, sin excusas.",
  description:
    "Receta auténtica de tiramisú italiano: aprendé a hacer el tiramisú original con mascarpone, café espresso, savoiardi, huevo, azúcar y cacao. Técnica paso a paso y secretos del postre más famoso de Italia.",
  image: "/images/recipes/tiramisu.jpg",
  imageAlt: "Porción de tiramisú casero con capa de cacao amargo sobre crema de mascarpone",
  region: "Véneto",
  prepTimeMin: 30,
  cookTimeMin: 0,
  servings: 8,
  difficulty: "fácil",
  category: "postre",
  keywords: [
    "tiramisú",
    "tiramisu",
    "tiramisù",
    "tiramisu italiano",
    "receta tiramisu auténtico",
    "tiramisu clásico",
    "postre italiano",
  ],
  intro: [
    "El tiramisú original no lleva crema de leche, ni gelatina, ni queso crema. Lleva cinco ingredientes: mascarpone, huevo, azúcar, café espresso y savoiardi. Más cacao amargo para terminar.",
    "Su aparente simplicidad esconde dos puntos críticos: montar bien las claras a nieve y elegir un mascarpone fresco y denso. El resto es paciencia y un buen café.",
  ],
  ingredients: [
    {
      label: "Mascarpone",
      quantity: 500,
      unit: "g",
      keywords: ["mascarpone", "ricotta"],
      negativeKeywords: ["girasoli", "tortelloni", "tortellini", "ravioli", "cappelleti"],
      note: "El mascarpone es único — ricotta es un reemplazo de emergencia, cambia la textura.",
      hero: true,
    },
    {
      label: "Savoiardi",
      quantity: 300,
      unit: "g",
      keywords: [
        "savoiardi",
        "vainillas",
        "ladyfingers",
        "cantuccini",
        "pavesini",
        "bizcochos",
      ],
      note: "Los savoiardi italianos son más secos que las vainillas comunes y absorben mejor el café.",
    },
    {
      label: "Café espresso",
      quantity: 400,
      unit: "ml",
      keywords: [
        "caffè",
        "café",
        "espresso",
        "caffe",
        "moka",
        "lavazza",
        "illy",
        "napoletano",
        "arabica",
      ],
      note: "Preparado en cafetera moka o máquina espresso. Debe estar frío antes de usar.",
    },
    {
      label: "Huevos frescos",
      quantity: 4,
      unit: "unidades",
      note: "Se usan crudos — que sean muy frescos. Si te preocupa la salmonella, usá huevos pasteurizados.",
    },
    {
      label: "Azúcar",
      quantity: 100,
      unit: "g",
    },
    {
      label: "Cacao amargo en polvo",
      quantity: 30,
      unit: "g",
      keywords: ["cacao amargo", "cacao en polvo", "cacao amaro", "cacao"],
    },
    {
      label: "Marsala seco (opcional)",
      quantity: 2,
      unit: "cdas",
      keywords: ["marsala", "vino marsala", "amaretto", "chianti"],
      note: "Tradicional en Véneto; también funcionan amaretto o rum oscuro.",
    },
  ],
  steps: [
    "Preparar el café: hacé 400 ml de espresso fuerte. Si usás cafetera italiana, necesitás al menos 2 tandas. Pasalo a un plato hondo o recipiente amplio y dejalo enfriar a temperatura ambiente. Agregá el marsala si lo vas a usar.",
    "Separar las claras de las yemas en dos bowls distintos. Las claras deben quedar sin rastro de yema (si hay, no montan).",
    "Batir las yemas con la mitad del azúcar (50 g) hasta que tripliquen su volumen y queden pálidas y esponjosas. Se nota cuando al levantar el batidor, la cinta tarda 3 segundos en caer.",
    "Agregar el mascarpone a las yemas batidas en tres tandas, integrando con espátula de abajo hacia arriba. La mezcla debe quedar densa y lisa.",
    "En un bowl limpio y seco, batir las claras a nieve. Cuando empiecen a espumar, sumá el azúcar restante en hilo. Seguí batiendo hasta pico firme brillante.",
    "Incorporar las claras al mascarpone en tres tandas, con movimientos envolventes suaves de abajo hacia arriba. No las integres de golpe o perdés el aire.",
    "Armar el tiramisú: mojá cada savoiardi en el café 1 segundo por lado — ni más, porque se deshace. Disponelos en el fondo de una fuente rectangular de 25×20 cm.",
    "Cubrir con la mitad de la crema de mascarpone, alisando con espátula. Segunda capa de savoiardi mojados, segunda capa de crema.",
    "Llevar a heladera mínimo 6 horas, idealmente una noche. El tiramisú mejora 24 horas después de hecho.",
    "Antes de servir, espolvoreá abundante cacao amargo con un tamiz por arriba. El cacao se pone al último momento, no antes — si no, se humedece y pierde el contraste.",
  ],
  tips: [
    "El mascarpone debe estar a temperatura ambiente y bien fresco. Si lo comprás y lo usás el mismo día, mejor.",
    "La proporción importa: por cada huevo, 125 g de mascarpone y 25 g de azúcar. Escalá desde ahí.",
    "Si sobra tiramisú, aguanta hasta 3 días en heladera tapado con film. Ganado — el sabor se intensifica.",
    "No reemplaces el mascarpone por ricotta o queso crema: es un postre diferente. El mascarpone tiene 40% de grasa y textura única.",
  ],
  history:
    "El tiramisú es uno de los postres italianos más jóvenes: surgió en los años 60 en el restaurante Le Beccherie de Treviso, Véneto, creado por la pastelera Alba Campeol y su ayudante Roberto Linguanotto. El nombre viene del véneto tiramesù, literalmente levantáme, por el efecto energético del café y el azúcar. En 2017 la región del Véneto lo registró oficialmente como prodotto agroalimentare tradizionale (PAT) italiano. Desde 2013 existe el campeonato mundial de tiramisú en Treviso — la Tiramisù World Cup — que premia la versión más fiel a la receta original.",
  pairingKeywords: [
    "panettone",
    "pandoro",
    "cantuccini",
    "baci",
    "bombon",
    "gianduitto",
    "amaretti",
    "biscotti",
    "amarena",
    "moscato",
    "prosecco",
    "marsala",
  ],
  publishedAt: "2026-04-13",
};
